FROM node:15.10.0-stretch-slim as build
WORKDIR /app
COPY ./ .
RUN npm i && npm run build

FROM nginx:alpine
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html
RUN ls -l /usr/share/nginx/html
