FROM node:13.8.0-stretch-slim as build-stage

WORKDIR /app
COPY ./frontend .
RUN npm ci --cache .npm --prefer-offline && npm run build

FROM nginx:1.16.0-alpine
#RUN rm -rf /etc/nginx/conf.d/default.conf
#COPY ./client/nginx/site.conf /etc/nginx/conf.d/site.conf
#COPY ./client/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage /app/build /usr/share/nginx/html
RUN ls -l /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
